package com.bao.model;

public class TOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Sat Aug 12 15:20:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.name
     *
     * @mbg.generated Sat Aug 12 15:20:13 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Sat Aug 12 15:20:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Sat Aug 12 15:20:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.name
     *
     * @return the value of t_order.name
     *
     * @mbg.generated Sat Aug 12 15:20:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.name
     *
     * @param name the value for t_order.name
     *
     * @mbg.generated Sat Aug 12 15:20:13 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}